# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#target 'Carrot_Market_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for Carrot_Market_iOS

#end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Carrot_Market_iOS' do
    pod 'JJFloatingActionButton'
end
